name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: go.mod

      - name: Build (amd64)
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /dev/null ./main.go

      - name: Build (arm64)
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o /dev/null ./main.go